[versions]
# libraries
annotations = "24.0.1"
groovyConsole="19.0.3"

# plugins
dokka = "1.8.10"
kotlin = "1.8.21"
changelog = "2.0.0"
gradleIntelliJPlugin = "1.14.0"
qodana = "0.1.13"
kover = "0.6.1"

[libraries]
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }
groovyConsoleApi = { group = "be.orbinson.aem", name = "aem-groovy-console-api", version.ref =  "groovyConsole"}
groovyConsoleBundle = { group = "be.orbinson.aem", name = "aem-groovy-console-bundle", version.ref =  "groovyConsole"}

[bundles]
groovyConsole = ["groovyConsoleApi", "groovyConsoleBundle"]

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
gradleIntelliJPlugin = { id = "org.jetbrains.intellij", version.ref = "gradleIntelliJPlugin" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
